import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;

public class ParserFormats {
    List<SimpleDateFormat> listDateFormatEn;

    public ParserFormats(){
        listDateFormatEn = Arrays.asList(
        new SimpleDateFormat("MM dd, yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMM dd, yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMMM dd, yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMMMM dd, yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MM dd. yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMM dd. yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMMM dd. yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMMMM dd. yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MM dd yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMM dd yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMMM dd yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMMMM dd yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MM-dd-yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMM-dd-yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMMM-dd-yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMMMM-dd-yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MM/dd/yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMM/dd/yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMMM/dd/yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMMMM/dd/yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMM.dd.yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMMM.dd.yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MMMMM.dd.yyyy", Locale.ENGLISH),
        new SimpleDateFormat("MM dd, yy", Locale.ENGLISH),
        new SimpleDateFormat("MMM dd, yy", Locale.ENGLISH),
        new SimpleDateFormat("MMMM dd, yy", Locale.ENGLISH),
        new SimpleDateFormat("MMMMM dd, yy", Locale.ENGLISH),
        new SimpleDateFormat("MM dd. yy", Locale.ENGLISH),
        new SimpleDateFormat("MMM dd. yy", Locale.ENGLISH),
        new SimpleDateFormat("MMMM dd. yy", Locale.ENGLISH),
        new SimpleDateFormat("MMMMM dd. yy", Locale.ENGLISH),
        new SimpleDateFormat("MM dd yy", Locale.ENGLISH),
        new SimpleDateFormat("MMM dd yy", Locale.ENGLISH),
        new SimpleDateFormat("MMMM dd yy", Locale.ENGLISH),
        new SimpleDateFormat("MMMMM dd yy", Locale.ENGLISH),
        new SimpleDateFormat("MM-dd-yy", Locale.ENGLISH),
        new SimpleDateFormat("MMM-dd-yy", Locale.ENGLISH),
        new SimpleDateFormat("MMMM-dd-yy", Locale.ENGLISH),
        new SimpleDateFormat("MMMMM-dd-yy", Locale.ENGLISH),
        new SimpleDateFormat("MM/dd/yy", Locale.ENGLISH),
        new SimpleDateFormat("MMM/dd/yy", Locale.ENGLISH),
        new SimpleDateFormat("MMMM/dd/yy", Locale.ENGLISH),
        new SimpleDateFormat("MMMMM/dd/yy", Locale.ENGLISH),
        new SimpleDateFormat("MMM.dd.yy", Locale.ENGLISH),
        new SimpleDateFormat("MMMM.dd.yy", Locale.ENGLISH),
        new SimpleDateFormat("MMMMM.dd.yy", Locale.ENGLISH),
        new SimpleDateFormat("dd.MM.yy", Locale.ENGLISH),
        new SimpleDateFormat("dd.MMM.yy", Locale.ENGLISH),
        new SimpleDateFormat("dd.MMMM.yy", Locale.ENGLISH),
        new SimpleDateFormat("dd.MMMMM.yy", Locale.ENGLISH),
        new SimpleDateFormat("dd MMM yyyy", Locale.ENGLISH),
        new SimpleDateFormat("dd MMMM yyyy", Locale.ENGLISH),
        new SimpleDateFormat("dd MMMMM yyyy", Locale.ENGLISH),
        new SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH),
        new SimpleDateFormat("dd-MMMM-yyyy", Locale.ENGLISH),
        new SimpleDateFormat("dd-MMMMM-yyyy", Locale.ENGLISH),
        new SimpleDateFormat("dd MMM yy", Locale.ENGLISH),
        new SimpleDateFormat("dd MMMM yy", Locale.ENGLISH),
        new SimpleDateFormat("dd MMMMM yy", Locale.ENGLISH),
        new SimpleDateFormat("dd-MMM-yy", Locale.ENGLISH),
        new SimpleDateFormat("dd-MMMM-yy", Locale.ENGLISH),
        new SimpleDateFormat("dd-MMMMM-yy", Locale.ENGLISH),
        new SimpleDateFormat("yyyy MM dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy MMM dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy MMMM dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy MMMMM dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy-MMM-dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy-MMMM-dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy-MMMMM-dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy/MM/dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy/MMM/dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy/MMMM/dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy/MMMMM/dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy.MM.dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy.MMM.dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy.MMMM.dd", Locale.ENGLISH),
        new SimpleDateFormat("yyyy.MMMMM.dd", Locale.ENGLISH));
    }

    public List<SimpleDateFormat> SimpleDateFormatListing() {return listDateFormatEn; }
}
